// Vendor an immutable bender-delivery-zones release into src/vendor.
// Copies the release files verbatim (LF) and generates a single embedded TS
// module (dataset.generated.ts) that carries the RAW file texts as strings, so
// the fail-closed validator can re-hash them and so the data loads identically
// under `next build` and `node --test` (where JSON/`@/` value imports break).
//
// Usage: node scripts/vendor-zones.mjs <path-to-release-dir>
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const releaseDir = process.argv[2];
if (!releaseDir) {
  console.error("usage: node scripts/vendor-zones.mjs <release-dir>");
  process.exit(2);
}

const here = dirname(fileURLToPath(import.meta.url));
const vendorDir = join(here, "..", "src", "vendor", "bender-zones-v1.1");

// Files copied verbatim into the vendor dir. The embedded TS carries the JSON
// ones so runtime can parse + hash them without a JSON import.
const EMBED = [
  "manifest.json",
  "address-registry.json",
  "admin-qa-objects.json",
  "street-index.json",
  "zone-polygons.geojson",
  "schemas/zone-release.schema.json",
];
const COPY_ONLY = [
  "CHECKSUMS.sha256",
  "IMMUTABLE",
  "varnita-village-no-delivery.geojson",
  "varnita-admin-reference.geojson",
  "severny-route-qa.geojson",
];

function readLf(rel) {
  return readFileSync(join(releaseDir, rel), "utf-8").replace(/\r\n/g, "\n");
}
function sha256(text) {
  return createHash("sha256").update(text, "utf-8").digest("hex");
}

rmSync(vendorDir, { recursive: true, force: true });
mkdirSync(join(vendorDir, "schemas"), { recursive: true });

const manifest = JSON.parse(readLf("manifest.json"));
const declared = new Map(manifest.files.map((f) => [f.path, f.sha256]));

// Copy every file verbatim and sanity-check embedded/declared checksums here so
// a mis-vendored file is caught at vendor time, not only at runtime.
for (const rel of [...EMBED, ...COPY_ONLY]) {
  const text = readLf(rel);
  const dest = join(vendorDir, rel);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, text, { encoding: "utf-8" });
  if (declared.has(rel)) {
    const got = sha256(text);
    if (got !== declared.get(rel)) {
      throw new Error(`checksum mismatch vendoring ${rel}: ${got} != ${declared.get(rel)}`);
    }
  }
}

const embed = {};
for (const rel of EMBED) embed[rel] = readLf(rel);
embed["CHECKSUMS.sha256"] = readLf("CHECKSUMS.sha256");

const lines = [];
lines.push("// GENERATED by scripts/vendor-zones.mjs — do not edit by hand.");
lines.push(`// Vendored immutable release ${manifest.release_id} (${manifest.version}).`);
lines.push("// Zones only, no prices. Raw file texts are embedded verbatim so the");
lines.push("// fail-closed validator can re-hash them (crypto over the exact bytes).");
lines.push("");
lines.push("export const VENDORED_RELEASE_ID = " + JSON.stringify(manifest.release_id) + ";");
lines.push("export const VENDORED_VERSION = " + JSON.stringify(manifest.version) + ";");
lines.push("");
lines.push("/** Raw file text keyed by release-relative path, exactly as checksummed. */");
lines.push("export const RAW_FILES: Record<string, string> = {");
for (const [rel, text] of Object.entries(embed)) {
  lines.push(`  ${JSON.stringify(rel)}: ${JSON.stringify(text)},`);
}
lines.push("};");
lines.push("");
writeFileSync(join(vendorDir, "dataset.generated.ts"), lines.join("\n") + "\n", {
  encoding: "utf-8",
});

console.log(
  `vendored ${manifest.release_id} ${manifest.version}: ` +
    `${Object.keys(embed).length} embedded, ${EMBED.length + COPY_ONLY.length} copied, ` +
    `verified_address_count=${manifest.verified_address_count}`,
);
